config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users,
    controllers: {:registrations => "user/registrations"}
  resources :indices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end
  root 'indices#home'
  get "dashboard", to:  "companies#index"
  get 'home', to: 'indices#home'
  get 'audit', to: 'companies#audit'

  get 'venue', to: "venues#index"
  get "display_venue", to: "venues#show"

  get "getall/all_venues", to: "venues#return_all_venues"

  post 'set_company_capacity', to: 'venues#set_company_capacity'
  post 'change_page', to: 'venues#change_page_percentage_full'
  post 'add_patron', to: 'indices#add_patron_to_venue'
  post 'contact_us', to: 'indices#contact_us'
  post 'request_company', to: 'indices#request_company'
  post 'message_patron', to: 'companies#message_patron', as: "message_patron"
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :company
end

app/controllers/venues_controller.rb
require 'net/http'
require 'uri'
class VenuesController < ApplicationController
  before_action :authenticate_user!, except: [:return_all_venues]


  # GET /venues
  # GET /venues.json
  def index
    render(:layout => "layouts/default")
    flash[:notice] = current_user.company.name
  end

  def set_company_capacity
    if current_user.company.update(percentage_full:params[:venue_capacity])
        # this function we need to take in the param of 1, 2, or 3. Where 1 is at capacity, 2 is filling up fast
        # 3 we are full and are about to crack a leak.
      if current_user.company.percentage_full == 0
        Patron.first.text_waitlist(current_user)
        Audit.create(venue_name: current_user.company.name, venue_capacity: 0)
      elsif current_user.company.percentage_full == 50
        Patron.first.text_waitlist(current_user)
        Audit.create(venue_name: current_user.company.name, venue_capacity: 50)
      end
      if current_user.company.percentage_full ==100
        Audit.create(venue_name: current_user.company.name, venue_capacity: 100)
      end
      respond_to do |format|
        format.html
        format.js { render js: ""}
      end
    end
  end

  def show
    render(:layout => "layouts/default")
    flash[:notice] = current_user.company.name
  end

  def change_page_percentage_full
    if current_user.company.percentage_full == 0
      respond_to do |format|
        format.html
        format.js { render js: "document.getElementById('available').style='display: block;'
          document.getElementById('almost_out').style='display: none;'
          document.getElementById('out').style='display: none;'"}
        end
    elsif current_user.company.percentage_full == 50
      respond_to do |format|
        format.html
        format.js { render js: "document.getElementById('available').style='display: none;'
          document.getElementById('almost_out').style='display: block;'
          document.getElementById('out').style='display: none;'"}
        end
    else
      respond_to do |format|
        format.html
        format.js { render js: "document.getElementById('available').style='display: none;'
          document.getElementById('almost_out').style='display: none;'
          document.getElementById('out').style='display: block;'"}
        end
      end
  end

  def return_all_venues

    @venues = Company.all
    @venues.each do |u|
      return_open_places(u)
      # if u.places_id != nil
      #   return_open(u.places_id)
      #   print u.updated_at
      # end
    end
    @venues = Company.all
    @userlist = @venues.map do |u|
      if u.is_open == true
        logger.debug u.name
        link = u.link
        @max_cap = u.capacity
        @per_full = (u.percentage_full)
        @percentage = @per_full
        if @percentage == 100
          @color = "red"
        elsif @percentage == 50
          @color = "orange"
        else
          @color = "green"
        end
        if u.is_active == false
          @color = "gray"
            { :id=>u.id, :name => u.name, :phone_number => u.phone_number, :address => u.address, :capacity => @percentage, :link => u.link, :color=>@color, long: u.lng, lat: u.lat }
        end
          { :id=>u.id, :name => u.name, :phone_number => u.phone_number, :address => u.address, :capacity => @percentage, :link => u.link, :color=>@color, long: u.lng, lat: u.lat }
      else
        if u.is_active == false
          @color = "gray"
            { :id=>u.id, :name => u.name, :phone_number => u.phone_number, :address => u.address, :capacity => @percentage, :link => u.link, :color=>@color, long: u.lng, lat: u.lat }
        else
          @color = "white"
        end
          { :id=>u.id, :name => u.name, :phone_number => u.phone_number, :address => u.address, :capacity => @percentage, :link => u.link, :color=>@color, long: u.lng, lat: u.lat }
      end
    end



    @json = @userlist.to_json
    respond_to do |format|
      format.html { render json: @json, status: 200 }
      format.json {render json: @json, status: 200}
    end
  end

  def return_open(places_id)
    logger.debug places_id
    uri = URI.parse("https://maps.googleapis.com/maps/api/place/details/json?place_id=#{places_id}&fields=name,rating,formatted_phone_number,opening_hours,formatted_address&key=AIzaSyDHvVaqvV6oKDo7E30tlWmI7D28jTU3EGQ")
    response = Net::HTTP.get_response(uri)
    @response = JSON(response.body)
    logger.debug @response
    logger.debug places_id
    if @response["status"] == "INVALID_REQUEST" or @response.empty?
      @company = Company.find_by(places_id: places_id)
      @company.update(is_open: false, update_number: @company.update_number+1);
      return false
    else
      if @response["result"]["opening_hours"].nil? == false and @response["result"]["opening_hours"]["open_now"] == true
        @company = Company.find_by(places_id: places_id)
        @company.update(is_open: true, update_number: @company.update_number+1);
      else
        @company = Company.find_by(places_id: places_id)
        @company.update(is_open: false, update_number: @company.update_number+1);
      end
      if @response["result"]["opening_hours"].nil? == true
        @company = Company.find_by(places_id: places_id)
        @company.update(is_open: true, update_number: @company.update_number+1);
      end
    end
  end

  def return_open_places(company)
    if company.monday_open.nil? == false && company.monday_closed.nil? == false  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  > company.monday_open.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i < company.monday_closed.to_i  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Monday"
      company.update(is_open: true)
      return true
    elsif company.tuesday_open.nil? == false && company.tuesday_closed.nil? == false  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i > company.tuesday_open.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  < company.tuesday_closed.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Tuesday"
      company.update(is_open: true)
      return true
    elsif company.wednesday_open.nil? == false && company.wednesday_closed.nil? == false && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  > company.wednesday_open.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  < company.wednesday_closed.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Wednesday"
      company.update(is_open: true)
      return true
    elsif company.thursday_open.nil? == false && company.thursday_closed.nil? == false  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i > company.thursday_open.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  < company.thursday_closed.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Thursday"
      logger.debug company.name

      company.update(is_open: true)
      return true
    elsif company.friday_open.nil? == false && company.friday_closed.nil? == false  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  > company.friday_open.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  < company.friday_closed.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Friday"
      company.update(is_open: true)
      return true
    elsif company.saturday_open.nil? == false && company.saturday_closed.nil? == false  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  > company.saturday_open.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  < company.saturday_closed.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Saturday"
      company.update(is_open: true)
      return true
    elsif company.sunday_open.nil? == false && company.sunday_closed.nil? == false  && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  > company.sunday_open.to_i.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  < company.sunday_closed.to_i && Time.now.in_time_zone("Sydney").strftime("%H%M").to_i  != 2359 && Date.today.strftime('%A') == "Sunday"
      company.update(is_open: true)
      return true
    else
      company.update(is_open: false)
      return false
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/index.html.erb
<div class = "row space_avaliable" id="available" onclick="set_venue_status(0)">

</div>
<div class = "row space_almost_out" id="almost_out" onclick="set_venue_status(1)">

</div>
<div class = "row space_not_avaliable" id="out" onclick="set_venue_status(2)">

</div>
<script type="text/javascript">
  function set_venue_status(status){
    if( status == 0){
      document.getElementById('available').style="opacity: 1";
      document.getElementById('almost_out').style="opacity: 0.5";
      document.getElementById('out').style="opacity: 0.5";
      $.ajax({
        type: "POST",
        url: "<%=set_company_capacity_path%>",
        data: {"venue_capacity":"0"}
      });


    }
    if( status == 1){
      document.getElementById('available').style="opacity: 0.5";
      document.getElementById('almost_out').style="opacity: 1";
      document.getElementById('out').style="opacity: 0.5";
      $.ajax({
        type: "POST",
        url: "<%=set_company_capacity_path%>",
        data: {"venue_capacity":"50"}
      });
    }
    if( status == 2){
      document.getElementById('available').style="opacity: 0.5";
      document.getElementById('almost_out').style="opacity: 0.5";
      document.getElementById('out').style="opacity: 1";
      $.ajax({
        type: "POST",
        url: "<%=set_company_capacity_path%>",
        data: {"venue_capacity":"100"}
      });
    }
  }

</script>

app/views/venues/show.html.erb
<%if current_user.company.percentage_full == 0%>
  <div class = "row space_avaliable-100 show-div" style="z-index:-1;" id="available" onclick="set_venue_status(0)">
    <div style='margin:auto; text-align: center;'>
      <h1 style="color: white; top:33vh; position: relative;">
        There's plenty of room. Come on in!
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
  <div class = "row space_almost_out-100 hide-div" id="almost_out" onclick="set_venue_status(1)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        Walkin's & small groups welcome
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
  <div class = "row space_not_avaliable-100 hide-div" id="out" onclick="set_venue_status(2)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        FULL <br>
        Register now for SMS alerts.
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
<%end%>
<%if current_user.company.percentage_full == 100%>
  <div class = "row space_avaliable-100 hide-div" id="available" onclick="set_venue_status(0)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        There's plenty of room. Come on in!
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
  <div class = "row space_almost_out-100 hide-div" id="almost_out" onclick="set_venue_status(1)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        Walkin's & small groups welcome
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white; bottom: 0; position: absolute; text-align:center">FINDAVENUE.IO </h1>
    </div>
  </div>
  <div class = "row space_not_avaliable-100 show-div" id="out" onclick="set_venue_status(2)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        FULL <br> Register now for SMS alerts.
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
<%end%>
<%if current_user.company.percentage_full == 50%>
  <div class = "row space_avaliable-100 hide-div" id="available" onclick="set_venue_status(0)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;   top:33vh; position: relative;"">
        There's plenty of room. Come on in!
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
  <div class = "row space_almost_out-100 show-div" id="almost_out" onclick="set_venue_status(1)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        Walkin's & small groups welcome
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
  <div class = "row space_not_avaliable-100 hide-div" id="out" onclick="set_venue_status(2)">
    <div style='margin:auto;   text-align: center;'>
      <h1 style="color: white;  top:33vh; position: relative;"">
        <h1 style="font-size:900">FULL </h1><br> Register now for SMS alerts.
      </h1>
    </div>
    <div style="bottom: 0; position: absolute; left:40vw;">
      <h1 style="color:white">FINDAVENUE.IO </h1>
    </div>
  </div>
<%end%>

<script type="text/javascript">
  function update_path(){
    $.ajax({
      type: "POST",
      url: "<%=change_page_path%>",
      dataType: 'script'
    });
  }
  setInterval(function() {
    update_path()
  }, 5000);
</script>