config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users,
    controllers: {:registrations => "user/registrations"}
  resources :indices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end
  root 'indices#home'
  get "dashboard", to:  "companies#index"
  get 'home', to: 'indices#home'
  get 'audit', to: 'companies#audit'

  get 'venue', to: "venues#index"
  get "display_venue", to: "venues#show"

  get "getall/all_venues", to: "venues#return_all_venues"

  post 'set_company_capacity', to: 'venues#set_company_capacity'
  post 'change_page', to: 'venues#change_page_percentage_full'
  post 'add_patron', to: 'indices#add_patron_to_venue'
  post 'contact_us', to: 'indices#contact_us'
  post 'request_company', to: 'indices#request_company'
  post 'message_patron', to: 'companies#message_patron', as: "message_patron"
end

app/models/company.rb
class Company < ApplicationRecord

end

app/controllers/companies_controller.rb
require 'net/http'
require 'uri'
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_admin, except: [:index, :edit, :show, :destroy]
  layout "venues", :only => [ :venue_capcity]
  # GET /companies
  # GET /companies.json
  def index
    if current_user.admin == true
      @companies = Company.all
      @patrons = Patron.where(waitlist: true, created_at:  (Time.now - 3.hours)..Time.now)

    else
      @companies = Company.where(id: current_user.company_id)
      @patrons = Patron.where(company_id: current_user.company_id, waitlist: true, created_at:  (Time.now - 3.hours)..Time.now)

    end
  end

  def message_patron
    @patron = Patron.find(params['id'].to_i)
    if @patron.text_details(@patron.phone_number)
       @patron.update(waitlist: false)
      respond_to do |format|
          format.js { render js: "document.getElementById('message_patron-#{params['id']}').style.display='none';document.getElementById('message_success_patron-#{params['id']}').style.display='block';" }
        end
    end

  end

  def check_admin
    if current_user.admin? == false
      redirect_to root_path
    end
  end
  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  def audit
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    if current_user.admin == true
    elsif current_user.company_id != params[:id].to_i
      redirect_to root_path
    end
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @data = return_all_details(company_params[:places_id])
    respond_to do |format|
      if @company.save
        @company.update(rating: @data["result"]["rating"])
        @company.update(phone_number: @data["result"]["formatted_phone_number"])
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @data = return_all_details(company_params[:places_id])
    respond_to do |format|
      if @company.update(company_params)
        @company.update(rating: @data["result"]["rating"])
        @company.update(phone_number: @data["result"]["formatted_phone_number"])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def return_all_details(places_id)
      uri = URI.parse("https://maps.googleapis.com/maps/api/place/details/json?place_id=#{places_id}&fields=name,rating,formatted_phone_number,opening_hours,formatted_address&key=AIzaSyDHvVaqvV6oKDo7E30tlWmI7D28jTU3EGQ")
      response = Net::HTTP.get_response(uri)
      @response = JSON(response.body)
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
        @company = Company.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_url, :flash => { :alert => "Record not found." }
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:monday_open, :monday_closed, :tuesday_open, :tuesday_closed, :wednesday_open, :wednesday_closed, :thursday_open, :thursday_closed, :friday_open, :friday_closed, :saturday_open, :saturday_closed, :sunday_open, :sunday_closed, :name, :address, :lat, :lng, :phone_number, :link, :capacity, :places_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHvVaqvV6oKDo7E30tlWmI7D28jTU3EGQ&callback=initAutocomplete&libraries=places&v=weekly"
  defer>
</script>
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>


<%= form_for(@company, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @company.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h4>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div id="map" class="col-sm-10 col-lg-10"></div>

      <div class="col-sm-10">
        <%= f.text_field :address, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>

  </div>


  <div class="form-group">

      <%= f.label :lat, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :lat, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :lng, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :lng, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :phone_number, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :phone_number, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :link, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :link, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :capacity, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :capacity, class: "form-control" %>
      </div>
  </div>
  <div class="form-group">

      <%= f.label :places_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :places_id, class: "form-control", onchange: "populate_close_times(ChIJ21jHvkCuEmsR9E21XUGOtCE)"%>
      </div>

  </div>
  <!-- Monday -->
  <div class="form-group">

      <%= f.label :monday_open, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :monday_open, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :monday_closed, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :monday_closed, class: "form-control" %>
      </div>

  </div>
<!-- tuesday -->
  <div class="form-group">

      <%= f.label :tuesday_open, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :tuesday_open, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :tuesday_closed, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :tuesday_closed, class: "form-control" %>
      </div>

  </div>
  <!-- wednesday -->
    <div class="form-group">

        <%= f.label :wednesday_open, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :wednesday_open, class: "form-control" %>
        </div>

    </div>
    <div class="form-group">

        <%= f.label :wednesday_closed, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :wednesday_closed, class: "form-control" %>
        </div>

    </div>
    <!-- Thursday -->
      <div class="form-group">

          <%= f.label :thursday_open, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :thursday_open, class: "form-control" %>
          </div>

      </div>
      <div class="form-group">

          <%= f.label :thursday_closed, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :thursday_closed, class: "form-control" %>
          </div>

      </div>
      <!-- Friday -->
        <div class="form-group">

            <%= f.label :friday_open, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :friday_open, class: "form-control" %>
            </div>

        </div>
        <div class="form-group">

            <%= f.label :friday_closed, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :friday_closed, class: "form-control" %>
            </div>

        </div>
        <!-- saturday -->
          <div class="form-group">

              <%= f.label :saturday_open, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.text_field :saturday_open, class: "form-control" %>
              </div>

          </div>
          <div class="form-group">

              <%= f.label :saturday_closed, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.text_field :saturday_closed, class: "form-control" %>
              </div>

          </div>
          <!-- Sunday -->
            <div class="form-group">

                <%= f.label :sunday_open, class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_field :sunday_open, class: "form-control" %>
                </div>

            </div>
            <div class="form-group">

                <%= f.label :sunday_closed, class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_field :sunday_closed, class: "form-control" %>
                </div>
            </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


<script>
  // This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.
// This example requires the Places library. Include the libraries=places
// parameter when you first load the API. For example:
// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
function initAutocomplete() {
  const map = new google.maps.Map(document.getElementById("map"), {
    center: { lat: -33.8688, lng: 151.2195 },
    zoom: 13,
    mapTypeId: "roadmap"
  });
  // Create the search box and link it to the UI element.
  const input = document.getElementById("company_address");
  const searchBox = new google.maps.places.SearchBox(input);
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
  // Bias the SearchBox results towards current map's viewport.
  map.addListener("bounds_changed", () => {
    searchBox.setBounds(map.getBounds());
  });
  let markers = [];
  // Listen for the event fired when the user selects a prediction and retrieve
  // more details for that place.
  searchBox.addListener("places_changed", () => {
    const places = searchBox.getPlaces();

    if (places.length == 0) {
      return;
    }
    // Clear out the old markers.
    markers.forEach(marker => {
      marker.setMap(null);
    });
    markers = [];
    // For each place, get the icon, name and location.
    const bounds = new google.maps.LatLngBounds();
    places.forEach(place => {
      console.log(place)
      if (!place.geometry) {
        console.log("Returned place contains no geometry");
        return;
      }
      const icon = {
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(25, 25)
      };
      // Create a marker for each place.
      markers.push(
        new google.maps.Marker({
          map,
          icon,
          title: place.name,
          position: place.geometry.location
        })
      );

      if (place.geometry.viewport) {
        // Only geocodes have viewport.
        bounds.union(place.geometry.viewport);
        console.log(place.geometry.location.lat());
        document.getElementById("company_lat").value=place.geometry.location.lat();
        console.log(place.geometry.location.lng());
        document.getElementById("company_lng").value=place.geometry.location.lng();
        document.getElementById("company_phone_number").value=place['formatted_phone_number'];
        document.getElementById("company_address").value=place['formatted_address'];
        document.getElementById("company_name").value=place['name'];
        document.getElementById("company_places_id").value=place['place_id'];
      } else {
        bounds.extend(place.geometry.location);
        console.log(place.geometry.location);

      }
    });
    map.fitBounds(bounds);
  });
}

  </script>

app/views/companies/edit.html.erb
<div class="page-header">
  <%= link_to root_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @company, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing company</h1>
</div>

<%= render 'form' %>

app/views/companies/index.html.erb
<div class="page-header">
  <% if current_user.admin == true %>
    <%= link_to new_company_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Company
    <% end %>
  <% end %>
  <h1>Your Companies</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Lng</th>
            <th>Phone number</th>
            <th>Link</th>
            <th>Capacity</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <%= content_tag :tr, id: dom_id(company), class: dom_class(company) do %>
                      <td><%= company.name %></td>
                      <td><%= company.address %></td>
                      <td><%= company.lat %></td>
                      <td><%= company.lng %></td>
                      <td><%= company.phone_number %></td>
                      <td><%= company.link %></td>
                      <td><%= company.capacity %></td>
                    <td><%= link_to 'Show', company %></td>
          <td><%= link_to 'Edit', edit_company_path(company) %></td>
          <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<% if @patrons.empty? == false %>
<h1> Patrons on the waitlist </h1>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Phone Number</th>
            <%if current_user.admin == true%>
            <th> Company Name </th>
            <%end%>
            <th>Created at </th>
            <th> Updated At </th>
            <th> Send message </th>
      </tr>
    </thead>

    <tbody>
      <% @patrons.each do |company| %>
        <%= content_tag :tr, id: dom_id(company), class: dom_class(company) do %>
                      <td><%= company.first_name %></td>
                      <td><%= company.phone_number %></td>
                      <%if current_user.admin == true%>
                      <th><%=Company.find(company.company_id).name%></th>
                      <%end%>
                      <td><%= company.created_at %></td>
                      <td><%= company.updated_at %></td>
                      <td><form action = "<%=message_patron_path%>" id="message_patron-<%=company.id%>" data-remote='true'" method="post"  id="patron-<%=company.id%>">
                        <input type="hidden" name="id" value="<%=company.id%>">
                        <button type="submit" class="btn btn-primary">
                          Send Message
                        </button>

                      </form>
                      <p id="message_success_patron-<%=company.id%>" style="display:none;"> Message Sent </p>

                      </td>

        <% end %>
      <% end %>
    </tbody>
  </table>
  <%end%>
</div>
<script>
//Request Venue Details
$("#message_patron").submit(function(e) {

  e.preventDefault(); // avoid to execute the actual submit of the form.

  var form = $(this);
  var url = form.attr('action');

  $.ajax({
    type: "POST",
    url: url,
    data: form.serialize(), // serializes the form's elements.
    datatype: "script"
  });

});

</script>

app/views/companies/new.html.erb
<div class="page-header">
  <%= link_to root_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New company</h1>
</div>

<%= render 'form' %>

app/views/companies/show.html.erb
<div class="page-header">
  <%= link_to root_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_company_path(@company), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show company</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @company.name %></dd>

  <dt>Address:</dt>
  <dd><%= @company.address %></dd>

  <dt>Lat:</dt>
  <dd><%= @company.lat %></dd>

  <dt>Lng:</dt>
  <dd><%= @company.lng %></dd>

  <dt>Phone number:</dt>
  <dd><%= @company.phone_number %></dd>

  <dt>Link:</dt>
  <dd><%= @company.link %></dd>

  <dt>Capacity:</dt>
  <dd><%= @company.capacity %></dd>

</dl>