config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users,
    controllers: {:registrations => "user/registrations"}
  resources :indices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end
  root 'indices#home'
  get "dashboard", to:  "companies#index"
  get 'home', to: 'indices#home'
  get 'audit', to: 'companies#audit'

  get 'venue', to: "venues#index"
  get "display_venue", to: "venues#show"

  get "getall/all_venues", to: "venues#return_all_venues"

  post 'set_company_capacity', to: 'venues#set_company_capacity'
  post 'change_page', to: 'venues#change_page_percentage_full'
  post 'add_patron', to: 'indices#add_patron_to_venue'
  post 'contact_us', to: 'indices#contact_us'
  post 'request_company', to: 'indices#request_company'
  post 'message_patron', to: 'companies#message_patron', as: "message_patron"
end

app/controllers/indices_controller.rb
class IndicesController < ApplicationController
  before_action :authenticate_user!, except: [:home, :add_patron_to_venue]
  # GET /indices
  # GET /indices.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: CompanyDatatable.new(params)}
    end
  end

  def redirect_to_path
      path = case current_user.admin
    when true
      indices_path
    else
      company_path(current_user.company_id)
      # If you want to raise an exception or have a default root for users without roles
    end
    redirect_to path
  end

  def home
    render(:layout => "layouts/landingpage")
  end

  def contact_us
    ContactUsMailer.send_contact(params).deliver_now
  end

  def request_company
    ContactUsMailer.request_company(params).deliver_now
  end

  def add_patron_to_venue
    @patron = Patron.new(first_name: params[:first_name], phone_number: params[:phone_number], company_id: params[:company_id])
    if @patron.save
      respond_to do |format|
        format.html
        format.js { render js: "alert('added to waitlist')"}
      end
    end
  end

end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/views/indices/home.html.erb
<div id="venue_map" class="venue_type">
  <img class="logo" height="50px" width ="168px" src="https://images-findavenue.s3-ap-southeast-2.amazonaws.com/cos+black+v2.0.png">
  <div id="map_div" style="height: 80vh; color:black;"></div>
</div>
<script>

function initMap() {
			var settings = {
		"url": "<%=getall_all_venues_path%>",
		"method": "GET",
		"timeout": 0,
	};

	$.ajax(settings).done(function (response) {
		var maps_data = JSON.parse(response);
    var i = 0
    while(maps_data[i] ==null)
    {
      i++;
    }
    console.log(maps_data[i]);
		console.log(maps_data[i].lat);
    console.log(maps_data[i].lat);
		var myLatLng = {lat: parseFloat(maps_data[i].lat), lng: parseFloat(maps_data[i].long)};
    console.log(myLatLng);
			var map = new google.maps.Map(document.getElementById('map_div'), {
				zoom: 15,
				center: myLatLng,
				styles: [
    {
        "featureType": "administrative",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.attraction",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.government",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.school",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.school",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    }
]
			});

markers = [];
infowindows = [];
		//all markers
		//
		    for (i = i; i < maps_data.length; i++) {
          console.log(maps_data);
						var myLatLng = {lat: parseFloat(maps_data[i].lat), lng: parseFloat(maps_data[i].long)};
					  const infowindow = new google.maps.InfoWindow({
  				  	content: maps_data[i]["name"] + " | "
              + maps_data[i]["address"] + " | <p class='inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800' onclick=document.getElementById('venue_list').showModal();" +
               "onmouseover = document.getElementById('company_id').value="+maps_data[i]['id']+"> Pre Sign in & add yourself to the waitlist. </p>",
							position: { lat: parseFloat(maps_data[i].lat), lng: parseFloat(maps_data[i].long) },
 						});
					//infowindows.push(infowindow);
					//console.log(infowindows);
					if(maps_data[i]['color'] == "green"){
      		  marker = new google.maps.Marker({
            	position: new google.maps.LatLng(parseFloat(maps_data[i]['lat']), parseFloat(maps_data[i]['long'])),
            	map: map,
					  	title: maps_data[i]['name'],
							icon: 'https://images-findavenue.s3-ap-southeast-2.amazonaws.com/green-dot.png'
        		});
					  marker.addListener("click", function(mapsMouseEvent) {
							mark = returnMarker(markers, mapsMouseEvent.latLng);
							closeInfowindows(infowindows);
							infowindow.open(map, mark);
						});
					}
					else if(maps_data[i]['color'] == "orange"){
						 marker = new google.maps.Marker({
            	position: new google.maps.LatLng(parseFloat(maps_data[i]['lat']), parseFloat(maps_data[i]['long'])),
            	map: map,
					  	title: maps_data[i]['name'],
							icon: 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png'
        		});
					  marker.addListener("click", function(mapsMouseEvent) {
							mark = returnMarker(markers, mapsMouseEvent.latLng);
							closeInfowindows(infowindows);
							infowindow.open(map, mark);
						});
					}
					else if(maps_data[i]['color'] == "red"){
						 marker = new google.maps.Marker({
            	position: new google.maps.LatLng(parseFloat(maps_data[i]['lat']), parseFloat(maps_data[i]['long'])),
            	map: map,
					  	title: maps_data[i]['name'],
              icon: "https://images-findavenue.s3-ap-southeast-2.amazonaws.com/red-dot.png"
        		});

					  marker.addListener("click", function(mapsMouseEvent) {

							mark = returnMarker(markers, mapsMouseEvent.latLng);
							closeInfowindows(infowindows);
							infowindow.open(map, mark);
						});
					}
          else if(maps_data[i]['color'] == "gray"){
             marker = new google.maps.Marker({
              position: new google.maps.LatLng(parseFloat(maps_data[i]['lat']), parseFloat(maps_data[i]['long'])),
              map: map,
              title: maps_data[i]['name'],
              icon: "https://images-findavenue.s3-ap-southeast-2.amazonaws.com/gray-dot.png"
            });
            marker.addListener("click", function(mapsMouseEvent) {
              mark = returnMarker(markers, mapsMouseEvent.latLng);
              closeInfowindows(infowindows);
              infowindow.open(map, mark);
            });
          }
          else if(maps_data[i]['color'] == "white"){
             marker = new google.maps.Marker({
              position: new google.maps.LatLng(parseFloat(maps_data[i]['lat']), parseFloat(maps_data[i]['long'])),
              map: map,
              title: maps_data[i]['name'],
              icon: "https://images-findavenue.s3-ap-southeast-2.amazonaws.com/white-dot.png"
            });
            marker.addListener("click", function(mapsMouseEvent) {
              mark = returnMarker(markers, mapsMouseEvent.latLng);
              closeInfowindows(infowindows);
              infowindow.open(map, mark);
            });
          }
							// infowindow.open(map, marker);
							if(maps_data[i]['color'] == 'red'){
								infowindow.setContent(maps_data[i]["name"] + " | " + "<a style='color:blue;' href='http://maps.google.com/maps?q=" + encodeURIComponent( maps_data[i]["address"] ) + "' target='_blank'>"+  maps_data[i]["address"]  +  " </a> | <button class='inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800' onclick=toggleModal('modal-id');  onmouseover = document.getElementById('company_id').value="+maps_data[i]['id']+"> Join Waitlist. </button>" )
                  infowindows.push(infowindow);
								}
                if(maps_data[i]['color'] == 'gray'){
                  infowindow.setContent(maps_data[i]["name"] + " | " + maps_data[i]["address"] + " | <p class='' style='font-weight:bold;, text-align: center;' onmouseover = document.getElementById('company_id_request').value="+maps_data[i]['id']+"> Live capacity updates not active </p> | <a style='background:gray' href="+maps_data[i]['link']+" class='inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800'   target='_blank'> Covid Sign In! </p>" )
                    infowindows.push(infowindow);
                  }
                if(maps_data[i]['color'] == 'green' || maps_data[i]['color'] == 'green'  ){
                  infowindow.setContent(maps_data[i]["name"] + " | " + + "<a style='color:blue;' href='http://maps.google.com/maps?q=" + encodeURIComponent( maps_data[i]["address"] ) + "' target='_blank'>"+  maps_data[i]["address"]  +  " </a> | <a href="+maps_data[i]['link']+" class='inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800'   target='_blank'> Covid Sign In! </p>" )
                    infowindows.push(infowindow);
                  }
                  if(maps_data[i]['color'] == 'white' ){
                    infowindow.setContent(maps_data[i]["name"] + " | Closed" )
                      infowindows.push(infowindow);
                    }
                  if(maps_data[i]['color'] == 'orange' || maps_data[i]['color'] == 'green'  ){
                    infowindow.setContent(maps_data[i]["name"] + " | " + "<a style='color:blue;' href='http://maps.google.com/maps?q=" + encodeURIComponent( maps_data[i]["address"] ) + "' target='_blank'>"+  maps_data[i]["address"]  +  " </a> | <a href="+maps_data[i]['link']+" class='inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800'  target='_blank'> Covid Sign In! </p>" )
                      infowindows.push(infowindow);
                    }
							infowindows.push(infowindow);
  	  }

	});
}


function returnMarker(markers, info){
	var mark ="";
	for(i=0; i<markers.length; i++){
		//console.log("markers: " + markers[i].position.lat());
		//console.log("markers: " + markers[i].title);

		if((markers[i].position.lat() == info.lat()) && markers[i].position.lng() == info.lng()){
			mark = markers[i];
		}
	}

	return mark
}
function closeInfowindows(infowindows){
		for(i=0; i<infowindows.length; i++){
			infowindows[i].close();
	}
}
function openCity(cityName) {
  var i;
  var x = document.getElementsByClassName("venue_type");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
	if(cityName == 'venue_map'){
		document.getElementById('map_div').style.width="100%";
	}
  document.getElementById(cityName).style.display = "block";
}
  setInterval(function(){ initMap(); }, 500000);
</script>

<script defer="" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHvVaqvV6oKDo7E30tlWmI7D28jTU3EGQ&amp;callback=initMap">
</script>

 <!-- <p class='inline-flex items-center h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800' onclick=document.getElementById('request_venue').showModal();  onmouseover = document.getElementById('company_id_request').value="+maps_data[i]['id']+"> This venue is not active at this time. </p>" ) -->

app/views/indices/index.html.erb
<h1> Companies </h1>
<table id="company-datatable" class="display responsive nowrap" style="width:100%; margin:auto;" data-source="<%= dashboard_path(format: :json) %>">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Capacity</th>
			<th>Link</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>