config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users,
    controllers: {:registrations => "user/registrations"}
  resources :indices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  as :user do
    get "/register", to: "registrations#new", as: "register"
  end
  root 'indices#home'
  get "dashboard", to:  "companies#index"
  get 'home', to: 'indices#home'
  get 'audit', to: 'companies#audit'

  get 'venue', to: "venues#index"
  get "display_venue", to: "venues#show"

  get "getall/all_venues", to: "venues#return_all_venues"

  post 'set_company_capacity', to: 'venues#set_company_capacity'
  post 'change_page', to: 'venues#change_page_percentage_full'
  post 'add_patron', to: 'indices#add_patron_to_venue'
  post 'contact_us', to: 'indices#contact_us'
  post 'request_company', to: 'indices#request_company'
  post 'message_patron', to: 'companies#message_patron', as: "message_patron"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find a Venue</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5W8VKG2');</script>
<!-- End Google Tag Manager -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src=""https://www.googletagmanager.com/ns.html?id=GTM-5W8VKG2""
height=""0"" width=""0"" style=""display:none;visibility:hidden""></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->"
  <%if user_signed_in?%>
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="<%=root_path%>"> Find A Venue</a>

    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="<%=destroy_user_session_path%>" data-method="delete" >Sign out</a>
      </li>
    </ul>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse navbar-expand-lg navbar-light ">
          <ul class="list-group">
              <!-- /END Separator -->
              <!-- Menu with submenu -->
              <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-light list-group-item list-group-item-action flex-column align-items-start">
                  <div class="d-flex w-100 justify-content-start align-items-center">
                      <span class="fa fa-dashboard fa-fw mr-3"></span>
                      <span class="menu-collapsed">Companies</span>
                      <span class="submenu-icon ml-auto"></span>
                  </div>
              </a>
              <!-- Submenu content -->
              <div id='submenu1' class="collapse sidebar-submenu">
              <%if current_user.company_id != nil%>
                <a href="<%=venue_path%>" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Set Venue Status</span>
                </a>
                <a href="<%=display_venue_path%>" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">View Venue Status</span>
                </a>
                <!-- <a href="<%=audit_path%>" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">View Company Audit</span>
                </a> -->
              <%end%>
                <%if current_user.admin?%>
                  <a href="<%=new_company_path%>" class="list-group-item list-group-item-action bg-dark text-white">
                      <span class="menu-collapsed">Create Company</span>
                  </a>
                  <a href="<%=companies_path%>" class="list-group-item list-group-item-action bg-dark text-white">
                      <span class="menu-collapsed">View Companies</span>
                  </a>

                <%end%>

              </div>

              <!-- Menu with submenu -->
              <% if current_user.admin == true%>
              <a href="#submenu2" data-toggle="collapse" aria-expanded="false" class="bg-light list-group-item list-group-item-action flex-column align-items-start">
                  <div class="d-flex w-100 justify-content-start align-items-center">
                      <span class="fa fa-dashboard fa-fw mr-3"></span>
                      <span class="menu-collapsed">User</span>
                      <span class="submenu-icon ml-auto"></span>
                  </div>
              </a>
              <!-- Submenu content -->
              <div id='submenu2' class="collapse sidebar-submenu">
                  <a href="<%=new_user_registration_path%>" class="list-group-item list-group-item-action bg-dark text-white">
                      <span class="menu-collapsed">Create User</span>
                  </a>
              </div>
              <%end%>
            </ul>
            <footer class="nav-footer" style="bottom: 0">
              © 2021, <a href="www.findavenue.io">www.findavenue.io</a>
            </footer>
      </nav>


      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <%if current_user.nil? == true %><p class="notice h1"><%=current_user.company.name%></p><%end%>
        <p class="notice"><%= notice %></p>
        <%= yield %>
      </main>
      <%else%>
      <main role="main" class="col-md-12 col-lg-12 col-sm-12">
      <%if current_user.nil? == false %>  <p class="notice h1"><%=current_user.company.name%></p> <%end%>
        <p class="notice"><%= notice %></p>
        <%= yield %>
      </main>
      <%end%>
    </div>
  </div>
  </body>
</html>

app/views/layouts/default.html.erb
<html lang="en" dir="ltr" style="height:100vh">
  <head>
    <meta charset="utf-8">
    <title>Find a Venue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5W8VKG2');</script>
    <!-- End Google Tag Manager -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body style="height:100vh">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src=""https://www.googletagmanager.com/ns.html?id=GTM-5W8VKG2""
height=""0"" width=""0"" style=""display:none;visibility:hidden""></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->"
      <p class="notice h1"><%=current_user.company.name%></p>
    <% if flash[:alert].nil? == false %>
      <p class="alert"><%= alert %></p>
    <%end%>
    <%= yield %>

    <a href="<%=dashboard_path%>" class="float">
      <i class="fa fa-arrow-left my-float"></i>
    </a>
    <%= javascript_pack_tag 'venues', 'data-turbolinks-track': 'reload' %>
  </body>

  <script type="text/javascript">
    window.onload = maxWindow;

    function maxWindow() {
        window.moveTo(0, 0);

        if (document.all) {
            top.window.resizeTo(screen.availWidth, screen.availHeight);
        }

        else if (document.layers || document.getElementById) {
            if (top.window.outerHeight < screen.availHeight || top.window.outerWidth < screen.availWidth) {
                top.window.outerHeight = screen.availHeight;
                top.window.outerWidth = screen.availWidth;
            }
        }
    }
</script>
</html>